--验证性实验
SELECT * FROM C,SC

SELECT SNO,CNAME,SCORE
FROM C,SC
WHERE C.CNO=SC.CNO

SELECT S.SNO,SNAME,CNO,SCORE
FROM S,SC
WHERE S.SNO=SC.SNO
SELECT S.SNO,SNAME,SC.CNO,CNAME,SCORE
FROM S,SC,C
WHERE S.SNO=SC.SNO AND SC.CNO=C.CNO

INSERT INTO S (SNO,SNAME) VALUES('20000','ZXX')
SELECT S.SNO,SNAME,CNO,SCORE
FROM S 
LEFT OUTER JOIN SC ON S.SNO=SC.SNO

SELECT S.SNO,SNAME,CNO,SCORE 
FROM S, SC 
WHERE S.SNO=SC.SNO

SELECT S1.SNO
FROM S AS S1, S AS S2
WHERE S1.DEPT=S2.DEPT AND S2.SNAME='李勇'

SELECT SNO,CNO, SCORE FROM SC AS SC1 
WHERE SCORE <(SELECT MAX(SCORE) FROM SC AS SC2 
WHERE SC2.SNO=SC1.SNO)

SELECT SNO 
FROM S
WHERE DEPT IN 
(SELECT DEPT FROM S WHERE SNAME='李勇')

SELECT COUNT (*) FROM SC
WHERE CNO IN 
( SELECT CNO FROM C WHERE CNAME='数据库原理')

SELECT CNO,SNO,SCORE
FROM SC AS SC1
WHERE CNO='C01' AND SCORE >(
SELECT SCORE FROM SC AS SC2 
WHERE SC2.SNO=SC1.SNO AND SC2.CNO='C02')

SELECT SNO,SNAME 
FROM S
WHERE EXISTS
(SELECT * FROM SC WHERE CNO='C03')
GO 
SELECT SNO,SNAME FROM S

INSERT INTO C VALUES('C06','数据库安全',NULL,3)
SELECT SNO,SNAME 
FROM S
WHERE EXISTS
(SELECT * FROM SC WHERE CNO='C06')

SELECT * FROM C;

SELECT COUNT(*)
FROM SC
WHERE EXISTS
( SELECT * FROM C
 WHERE C.CNO=SC.CNO AND CNAME='数据库原理')

--设计性实验
--1)
SELECT SC.SNO, SC.CNO, SC.SCORE
FROM SC
INNER JOIN S ON SC.SNO = S.SNO
WHERE S.DEPT = '计算机系';
--2)
SELECT *
FROM SC
WHERE SCORE < (
    SELECT AVG(SCORE)
    FROM SC
    WHERE CNO = SC.CNO
)
--3)
SELECT S.SNO, C.CNAME, SC.SCORE
FROM S
INNER JOIN SC ON S.SNO = SC.SNO
INNER JOIN C ON SC.CNO = C.CNO
WHERE SC.CNO = 'C01'
ORDER BY S.SNO DESC, SC.SCORE ASC;
--4)
SELECT S.SNO, S.SNAME
FROM S
INNER JOIN SC ON S.SNO = SC.SNO
GROUP BY S.SNO, S.SNAME
HAVING COUNT(DISTINCT SC.CNO) >= 2;
--5)
SELECT DISTINCT SC.CNO
FROM S
INNER JOIN SC ON S.SNO = SC.SNO
WHERE S.AGE BETWEEN 20 AND 22 AND S.SEX = '男';
--6)
SELECT COUNT(DISTINCT S.SNO) AS StudentCount
FROM S
INNER JOIN SC ON S.SNO = SC.SNO
INNER JOIN C ON SC.CNO = C.CNO
WHERE C.CNAME = '数据结构';
--7）
SELECT S.SNO, S.SNAME
FROM S
INNER JOIN SC ON S.SNO = SC.SNO
GROUP BY S.SNO, S.SNAME
HAVING MIN(SC.SCORE) >= 80;