--验证性实验

--1
USE LMS
GO
SELECT * FROM S
INSERT INTO S(SNO,SNAME) VALUES('200300','Paulwen')
SELECT * FROM S

--2

CREATE TABLE SBAK(
SNO VARCHAR (10) NOT NULL,
SNAME VARCHAR(20),
DEPT VARCHAR(20),
AGE INT,
SEX CHAR(4));
GO
SELECT * FROM SBAK;
INSERT INTO SBAK select * from S
SELECT * FROM SBAK

CREATE TABLE CBAK (
CNO VARCHAR(10) NOT NULL,
CNAME VARCHAR(20),
CPNO VARCHAR(10),
CREDIT INT)
GO
INSERT INTO CBAK SELECT * FROM C
DELETE FROM CBAK WHERE CREDIT<4
SELECT * FROM CBAK

SELECT * FROM S
UPDATE S SET DEPT='CS' WHERE DEPT='计算机系'
GO
SELECT * FROM S

SELECT * FROM C
GO
CREATE INDEX ICNAME ON C(CNAME)
GO
SELECT * FROM C /*看数据表 */
SELECT * FROM C WITH(INDEX=ICNAME);

SELECT * FROM C
--GO
--CREATE CLUSTERED INDEX CICNO ON C(CNO)
GO
SELECT * FROM C

CREATE UNIQUE INDEX UISNO ON SC (SNO)
--执行后有什么结果？为什么会出现这个结果？
CREATE UNIQUE INDEX UISNO ON SC (SNO, CNO DESC)
--执行后有什么结果？SELECT * FROM S
GO
CREATE INDEX IAGESNO ON S(AGE DESC,SNO)
GO 
SELECT * FROM S
SELECT * FROM S WITH(INDEX =IAGESNO)SP_HELPINDEX 'S'DROP INDEX S.IAGESNO
GO
SP_HELPINDEX 'S'CREATE VIEW SHOWSNO
AS
SELECT S.SNO,SNAME,AVG(SCORE ) AS 平均成绩
FROM S,SC
WHERE S.SNO=SC.SNO
GROUP BY S.SNO,SNAME
GO 
SELECT * FROM SHOWSNO

CREATE VIEW VISDEPT
AS
SELECT * FROM S WHERE DEPT='信息系'

UPDATE VISDEPT
SET DEPT='IS'
GO 
SELECT * FROM VISDEPT

CREATE VIEW S_SUM
AS
SELECT SNO, SUM(SCORE) AS TOTALSCORE FROM SC
GROUP BY SNO
GO
UPDATE S_SUM SET TOTALSCORE=60

SELECT * FROM VISDEPT
DELETE FROM VISDEPT WHERE SEX='女'
SELECT * FROM VISDEPT
SELECT * FROM S


--设计性实验
--1
UPDATE S
SET DEPT = 'CS'
WHERE DEPT = '计算机系'

--2
-- 创建 SCNEW 表与 SC 表结构相同
SELECT *
INTO SCNEW
FROM SC
WHERE SCORE IS NULL;

SELECT * FROM SCNEW

--3

DELETE FROM SC
WHERE SCORE IS NULL;

SELECT * FROM SC

--4
SELECT * FROM S;

CREATE UNIQUE INDEX IX_SNAME ON S (SNAME);

--5
CREATE CLUSTERED INDEX CI_SNO ON S (SNO);

--6
CREATE INDEX IX_SNO_CNO ON SC (SNO ASC, CNO DESC);

--7
SELECT * FROM CourseStats;