USE LMS
CREATE TABLE Student(
SNO VARCHAR(10) NOT NULL, 
SNAME VARCHAR(20) NOT NULL, 
SEX CHAR(2), 
BIRTHDAY DATETIME)

INSERT INTO Student 
VALUES('200512','Josephine','F','1980-12-20')select * from Student;